// Generated by tools/drive_sdk_generator_runner.mjs from the owner-only Drive OpenAPI input.
// This file is outside generated/server-openapi so SDK ownership metadata does not pollute sdkgen output.

export const sdkMetadata = {
  name: "sdkwork-drive-backend-sdk",
  packageName: "sdkwork-drive-backend-sdk-generated-typescript",
  sdkOwner: "sdkwork-drive",
  apiAuthority: "sdkwork-drive.backend",
  language: "typescript",
  standardProfile: "sdkwork-v3",
  baseUrl: "http://127.0.0.1:18080",
  apiPrefix: "/backend/v3/api",
  sdkDependencies: [{"workspace":"sdkwork-iam-backend-sdk","role":"appbase-backend-management-capability","required":true,"dependencyMode":"consumer-sdk","apiPrefix":"/backend/v3/api","apiAuthority":"sdkwork-iam-backend-api","generatedTransportImportPolicy":"forbidden","packageByLanguage":{"typescript":"@sdkwork/iam-backend-sdk","rust":"sdkwork-iam-backend-sdk","java":"com.sdkwork:sdkwork-iam-backend-sdk","python":"sdkwork-iam-backend-sdk","go":"github.com/sdkwork/sdkwork-iam-backend-sdk"}}],
};

export const operations = {
  "auditEvents.list": { method: "GET", path: "/backend/v3/api/drive/audit_events" },
  "downloadPackages.list": { method: "GET", path: "/backend/v3/api/drive/download_packages" },
  "labels.create": { method: "POST", path: "/backend/v3/api/drive/labels" },
  "labels.delete": { method: "DELETE", path: "/backend/v3/api/drive/labels/{labelId}" },
  "labels.list": { method: "GET", path: "/backend/v3/api/drive/labels" },
  "labels.retrieve": { method: "GET", path: "/backend/v3/api/drive/labels/{labelId}" },
  "labels.update": { method: "PATCH", path: "/backend/v3/api/drive/labels/{labelId}" },
  "maintenance.abandonedUploadTaskSweep": { method: "POST", path: "/backend/v3/api/drive/maintenance/abandoned_upload_task_sweep" },
  "maintenance.expiredUploadContentSweep": { method: "POST", path: "/backend/v3/api/drive/maintenance/expired_upload_content_sweep" },
  "maintenance.jobs.list": { method: "GET", path: "/backend/v3/api/drive/maintenance/jobs" },
  "maintenance.objectSweep": { method: "POST", path: "/backend/v3/api/drive/maintenance/object_sweep" },
  "maintenance.uploadSessionSweep": { method: "POST", path: "/backend/v3/api/drive/maintenance/upload_session_sweep" },
  "quotas.retrieve": { method: "GET", path: "/backend/v3/api/drive/quotas" },
  "quotas.update": { method: "PUT", path: "/backend/v3/api/drive/quotas" },
  "sandboxGrants.create": { method: "POST", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}/grants" },
  "sandboxGrants.delete": { method: "DELETE", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}/grants/{grantId}" },
  "sandboxGrants.list": { method: "GET", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}/grants" },
  "sandboxGrants.retrieve": { method: "GET", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}/grants/{grantId}" },
  "sandboxGrants.update": { method: "PATCH", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}/grants/{grantId}" },
  "sandboxVolumes.create": { method: "POST", path: "/backend/v3/api/drive/sandbox_volumes" },
  "sandboxVolumes.delete": { method: "DELETE", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}" },
  "sandboxVolumes.list": { method: "GET", path: "/backend/v3/api/drive/sandbox_volumes" },
  "sandboxVolumes.retrieve": { method: "GET", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}" },
  "sandboxVolumes.update": { method: "PATCH", path: "/backend/v3/api/drive/sandbox_volumes/{sandboxId}" },
  "spaces.admin.list": { method: "GET", path: "/backend/v3/api/drive/spaces" },
} as const;
