// Generated by tools/drive_sdk_generator_runner.mjs from the owner-only Drive OpenAPI input.
// This file is outside generated/server-openapi so SDK ownership metadata does not pollute sdkgen output.

export const sdkMetadata = {
  name: "sdkwork-drive-admin-storage-sdk",
  packageName: "sdkwork-drive-admin-storage-sdk-generated-typescript",
  sdkOwner: "sdkwork-drive",
  apiAuthority: "sdkwork-drive.admin.storage",
  language: "typescript",
  standardProfile: "sdkwork-drive-admin-storage-v3",
  baseUrl: "http://127.0.0.1:18080",
  apiPrefix: "/backend/v3/api",
  sdkDependencies: [{"workspace":"sdkwork-iam-backend-sdk","role":"appbase-backend-management-capability","required":true,"dependencyMode":"consumer-sdk","apiPrefix":"/backend/v3/api","apiAuthority":"sdkwork-iam-backend-api","generatedTransportImportPolicy":"forbidden","packageByLanguage":{"typescript":"@sdkwork/iam-backend-sdk","rust":"sdkwork-iam-backend-sdk","java":"com.sdkwork:sdkwork-iam-backend-sdk","python":"sdkwork-iam-backend-sdk","go":"github.com/sdkwork/sdkwork-iam-backend-sdk"}}],
};

export const operations = {
  "storageProviderBindings.default.delete": { method: "DELETE", path: "/backend/v3/api/drive/storage/bindings/default" },
  "storageProviderBindings.default.retrieve": { method: "GET", path: "/backend/v3/api/drive/storage/bindings/default" },
  "storageProviderBindings.default.update": { method: "PUT", path: "/backend/v3/api/drive/storage/bindings/default" },
  "storageProviderBindings.list": { method: "GET", path: "/backend/v3/api/drive/storage/bindings" },
  "storageProviderKinds.initialize": { method: "POST", path: "/backend/v3/api/drive/storage/provider-kinds" },
  "storageProviderKinds.list": { method: "GET", path: "/backend/v3/api/drive/storage/provider-kinds" },
  "storageProviderKinds.update": { method: "PATCH", path: "/backend/v3/api/drive/storage/provider-kinds/{providerKind}" },
  "storageProviders.activate": { method: "POST", path: "/backend/v3/api/drive/storage/providers/{providerId}/activate" },
  "storageProviders.bucket.delete": { method: "DELETE", path: "/backend/v3/api/drive/storage/providers/{providerId}/bucket" },
  "storageProviders.bucket.retrieve": { method: "GET", path: "/backend/v3/api/drive/storage/providers/{providerId}/bucket" },
  "storageProviders.bucket.update": { method: "PUT", path: "/backend/v3/api/drive/storage/providers/{providerId}/bucket" },
  "storageProviders.buckets.list": { method: "GET", path: "/backend/v3/api/drive/storage/providers/{providerId}/buckets" },
  "storageProviders.capabilities.list": { method: "GET", path: "/backend/v3/api/drive/storage/providers/{providerId}/capabilities" },
  "storageProviders.create": { method: "POST", path: "/backend/v3/api/drive/storage/providers" },
  "storageProviders.credentials.rotate": { method: "POST", path: "/backend/v3/api/drive/storage/providers/{providerId}/credentials/rotate" },
  "storageProviders.deactivate": { method: "POST", path: "/backend/v3/api/drive/storage/providers/{providerId}/deactivate" },
  "storageProviders.delete": { method: "DELETE", path: "/backend/v3/api/drive/storage/providers/{providerId}" },
  "storageProviders.list": { method: "GET", path: "/backend/v3/api/drive/storage/providers" },
  "storageProviders.objects.content.retrieve": { method: "GET", path: "/backend/v3/api/drive/storage/providers/{providerId}/object-contents/{objectKey}" },
  "storageProviders.objects.content.update": { method: "PUT", path: "/backend/v3/api/drive/storage/providers/{providerId}/object-contents/{objectKey}" },
  "storageProviders.objects.copy": { method: "POST", path: "/backend/v3/api/drive/storage/providers/{providerId}/objects/copy" },
  "storageProviders.objects.delete": { method: "DELETE", path: "/backend/v3/api/drive/storage/providers/{providerId}/objects/{objectKey}" },
  "storageProviders.objects.list": { method: "GET", path: "/backend/v3/api/drive/storage/providers/{providerId}/objects" },
  "storageProviders.objects.retrieve": { method: "GET", path: "/backend/v3/api/drive/storage/providers/{providerId}/objects/{objectKey}" },
  "storageProviders.retrieve": { method: "GET", path: "/backend/v3/api/drive/storage/providers/{providerId}" },
  "storageProviders.test": { method: "POST", path: "/backend/v3/api/drive/storage/providers/{providerId}/test" },
  "storageProviders.update": { method: "PATCH", path: "/backend/v3/api/drive/storage/providers/{providerId}" },
} as const;
