// @generated by tools/gen_http_route_manifest_from_openapi.py - do not edit

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest, RateLimitTier};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/drive/node_versions/{nodeVersionId}/content",
        "drive",
        "driveResourceContent.retrieve",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
    HttpRoute::ingress_token(
        HttpMethod::Post,
        "/internal/v3/api/drive/resource_resolutions",
        "drive",
        "driveResources.resolve",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
    HttpRoute::ingress_token(
        HttpMethod::Post,
        "/internal/v3/api/drive/root_scope_subscriptions",
        "drive",
        "rootScopeSubscriptions.create",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/drive/root_scope_subscriptions/{subscriptionUuid}",
        "drive",
        "rootScopeSubscriptions.retrieve",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
    HttpRoute::ingress_token(
        HttpMethod::Put,
        "/internal/v3/api/drive/root_scope_subscriptions/{subscriptionUuid}/event_delivery",
        "drive",
        "rootScopeEventDeliveries.replace",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
    HttpRoute::ingress_token(
        HttpMethod::Get,
        "/internal/v3/api/drive/website_roots/{websiteRootUuid}",
        "drive",
        "websiteRoots.retrieve",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
    HttpRoute::ingress_token(
        HttpMethod::Put,
        "/internal/v3/api/drive/website_roots/{websiteRootUuid}/event_deliveries/{channelId}",
        "drive",
        "websiteRootEventDeliveries.replace",
    )
    .with_rate_limit_tier(RateLimitTier::Internal),
];

pub fn internal_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
