// Generated by tools/drive_sdk_generator_runner.mjs from the owner-only Drive OpenAPI input.
// This file is outside generated/server-openapi so SDK ownership metadata does not pollute sdkgen output.

export const sdkMetadata = {
  name: "sdkwork-drive-internal-sdk",
  packageName: "sdkwork-drive-internal-sdk-generated-typescript",
  sdkOwner: "sdkwork-drive",
  apiAuthority: "sdkwork-drive-internal-api",
  language: "typescript",
  standardProfile: "sdkwork-v3",
  baseUrl: "http://127.0.0.1:18080",
  apiPrefix: "/internal/v3/api",
  sdkDependencies: [],
};

export const operations = {
  "driveResourceContent.retrieve": { method: "GET", path: "/internal/v3/api/drive/node_versions/{nodeVersionId}/content" },
  "driveResources.resolve": { method: "POST", path: "/internal/v3/api/drive/resource_resolutions" },
  "rootScopeEventDeliveries.replace": { method: "PUT", path: "/internal/v3/api/drive/root_scope_subscriptions/{subscriptionUuid}/event_delivery" },
  "rootScopeSubscriptions.create": { method: "POST", path: "/internal/v3/api/drive/root_scope_subscriptions" },
  "rootScopeSubscriptions.retrieve": { method: "GET", path: "/internal/v3/api/drive/root_scope_subscriptions/{subscriptionUuid}" },
  "websiteRootEventDeliveries.replace": { method: "PUT", path: "/internal/v3/api/drive/website_roots/{websiteRootUuid}/event_deliveries/{channelId}" },
  "websiteRoots.retrieve": { method: "GET", path: "/internal/v3/api/drive/website_roots/{websiteRootUuid}" },
} as const;
