use axum::routing::{get, patch, post};
use axum::Router;

use crate::handlers::*;
use crate::state::AdminStorageState;

pub(crate) fn storage_drive_routes(prefix: &str) -> Router<AdminStorageState> {
    Router::new()
        .route(
            &format!("{prefix}/drive/storage/providers"),
            get(list_storage_providers).post(create_storage_provider),
        )
        .route(
            &format!("{prefix}/drive/storage/provider-kinds"),
            get(list_storage_provider_kinds).post(initialize_storage_provider_kinds),
        )
        .route(
            &format!("{prefix}/drive/storage/provider-kinds/{{provider_kind}}"),
            patch(set_storage_provider_kind_enabled),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}"),
            get(get_storage_provider)
                .patch(update_storage_provider)
                .delete(delete_storage_provider),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/capabilities"),
            get(get_storage_provider_capabilities),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/test"),
            post(test_storage_provider),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/activate"),
            post(activate_storage_provider),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/deactivate"),
            post(deactivate_storage_provider),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/credentials/rotate"),
            post(rotate_storage_provider_credentials),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/bucket"),
            get(head_storage_provider_bucket)
                .put(create_storage_provider_bucket)
                .delete(delete_storage_provider_bucket),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/buckets"),
            get(list_storage_provider_buckets),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/objects"),
            get(list_storage_provider_objects),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/objects/copy"),
            post(copy_storage_provider_object),
        )
        .route(
            &format!("{prefix}/drive/storage/providers/{{provider_id}}/objects/{{*object_key}}"),
            get(head_storage_provider_object).delete(delete_storage_provider_object),
        )
        .route(
            &format!(
                "{prefix}/drive/storage/providers/{{provider_id}}/object-contents/{{*object_key}}"
            ),
            get(read_storage_provider_object_content).put(write_storage_provider_object_content),
        )
        .route(
            &format!("{prefix}/drive/storage/bindings/default"),
            get(get_default_storage_provider_binding)
                .put(set_default_storage_provider_binding)
                .delete(delete_default_storage_provider_binding),
        )
        .route(
            &format!("{prefix}/drive/storage/bindings"),
            get(list_storage_provider_bindings),
        )
}
