const POSTGRES_CORE_SQL: &str = include_str!("../src/infrastructure/sql/postgres_core.sql");
const AUDIT_STORE: &str = include_str!("../src/infrastructure/sql/audit_store.rs");
const CHANGE_RECORDER: &str = include_str!("../src/infrastructure/change_recorder.rs");
const MAINTENANCE_STORE: &str = include_str!("../src/infrastructure/sql/maintenance_store.rs");
const UPLOADER_STORE: &str = include_str!("../src/infrastructure/sql/uploader_store.rs");

#[test]
fn drive_runtime_id_tables_do_not_use_database_allocated_ids() {
    for (path, source) in [("postgres_core.sql", POSTGRES_CORE_SQL)] {
        let upper = source.to_ascii_uppercase();
        for forbidden in [
            "AUTOINCREMENT",
            "BIGSERIAL",
            "GENERATED ALWAYS",
            "GENERATED BY DEFAULT",
            "IDENTITY",
            "NEXTVAL",
        ] {
            assert!(
                !upper.contains(forbidden),
                "{path} must not allocate runtime business IDs through {forbidden}"
            );
        }
    }
}

#[test]
fn drive_runtime_repositories_bind_explicit_ids_before_insert() {
    assert_insert_declares_id(
        AUDIT_STORE,
        "dr_drive_audit_event",
        "audit_store.rs must bind an explicit Snowflake id",
    );
    assert_insert_declares_id(
        MAINTENANCE_STORE,
        "dr_drive_maintenance_job",
        "maintenance_store.rs must bind an explicit Snowflake id",
    );
    assert_insert_declares_id(
        CHANGE_RECORDER,
        "dr_drive_change_log",
        "change_recorder.rs must bind an explicit Snowflake id",
    );
    assert_insert_declares_id(
        CHANGE_RECORDER,
        "dr_drive_domain_outbox",
        "change_recorder.rs must bind an explicit Snowflake id for domain outbox",
    );

    for (path, source) in [
        ("audit_store.rs", AUDIT_STORE),
        ("change_recorder.rs", CHANGE_RECORDER),
        ("maintenance_store.rs", MAINTENANCE_STORE),
        ("uploader_store.rs", UPLOADER_STORE),
    ] {
        assert!(
            !source.contains("RETURNING id"),
            "{path} must not depend on database-generated RETURNING id allocation"
        );
    }
}

#[tokio::test]
async fn postgres_runtime_id_tables_reject_missing_ids() {
    let Some((pool, _database_guard)) = sdkwork_drive_test_support::postgres_test_database().await
    else {
        return;
    };

    assert!(
        sqlx::query(
            "INSERT INTO dr_drive_change_log (
                tenant_id, space_id, node_id, sequence_no, event_type, actor_id
             ) VALUES (
                'tenant-runtime-id', 'space-runtime-id', NULL, 1,
                'node.changed', 'user-runtime-id'
             )",
        )
        .execute(&pool)
        .await
        .is_err(),
        "dr_drive_change_log must require an explicit runtime-generated id"
    );

    assert!(
        sqlx::query(
            "INSERT INTO dr_drive_audit_event (
                tenant_id, action, resource_type, resource_id, operator_id
             ) VALUES (
                'tenant-runtime-id', 'storage_provider.created',
                'storage_provider', 'provider-runtime-id', 'admin-runtime-id'
             )",
        )
        .execute(&pool)
        .await
        .is_err(),
        "dr_drive_audit_event must require an explicit runtime-generated id"
    );

    assert!(
        sqlx::query(
            "INSERT INTO dr_drive_maintenance_job (
                job_type, status, dry_run, scanned_count, affected_count,
                operator_id, started_at, finished_at
             ) VALUES (
                'object_sweep', 'completed', false, 0, 0, 'admin-runtime-id',
                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
             )",
        )
        .execute(&pool)
        .await
        .is_err(),
        "dr_drive_maintenance_job must require an explicit runtime-generated id"
    );
}

fn assert_insert_declares_id(source: &str, table_name: &str, message: &str) {
    let marker = format!("INSERT INTO {table_name}");
    let mut rest = source;
    let mut found = false;
    while let Some(position) = rest.find(&marker) {
        found = true;
        let block = &rest[position..];
        let values_position = block
            .find("VALUES")
            .unwrap_or_else(|| panic!("{table_name} insert must declare a VALUES block"));
        let insert_header = &block[..values_position];
        let columns_start = insert_header
            .find('(')
            .unwrap_or_else(|| panic!("{table_name} insert must declare columns"));
        let columns_end = insert_header[columns_start + 1..]
            .find(')')
            .map(|end| columns_start + 1 + end)
            .unwrap_or_else(|| panic!("{table_name} insert must close columns"));
        let declares_id = insert_header[columns_start + 1..columns_end]
            .split(',')
            .any(|column| column.trim().eq_ignore_ascii_case("id"));
        assert!(declares_id, "{message}");
        rest = &block[values_position + "VALUES".len()..];
    }
    assert!(
        found,
        "{table_name} insert must exist in the checked source"
    );
}
