#!/usr/bin/env python3
"""Generate http_route_manifest.rs from an OpenAPI document."""

from __future__ import annotations

import json
import sys
from pathlib import Path

METHOD_MAP = {
    "get": "Get",
    "post": "Post",
    "patch": "Patch",
    "delete": "Delete",
    "put": "Put",
}

AUTH_MAP = {
    "dual-token": "dual_token",
    "anonymous": "public",
    "refresh-token": "refresh_token",
    "api-key": "api_key",
    "oauth": "oauth",
    "open-api-flexible": "open_api_flexible",
    "ingress-token": "ingress_token",
}

RATE_LIMIT_TIER_MAP = {
    "auth-critical": "AuthCritical",
    "open-api-default": "OpenApiDefault",
    "upload": "Upload",
    "search": "Search",
    "bulk": "Bulk",
    "worker": "Worker",
    "internal": "Internal",
}


def load_openapi(openapi_path: Path) -> dict:
    source = openapi_path.read_text(encoding="utf-8")
    if openapi_path.suffix.lower() in {".yaml", ".yml"}:
        try:
            import yaml
        except ImportError as error:
            raise RuntimeError(
                "PyYAML is required to generate a route manifest from YAML OpenAPI"
            ) from error
        document = yaml.safe_load(source)
    else:
        document = json.loads(source)
    if not isinstance(document, dict):
        raise ValueError(f"OpenAPI root must be an object: {openapi_path}")
    return document


def load_routes(openapi_path: Path) -> list[tuple[str, str, str, str, str | None]]:
    document = load_openapi(openapi_path)
    routes: list[tuple[str, str, str, str, str | None]] = []
    for path, methods in document.get("paths", {}).items():
        for method, operation in methods.items():
            if method not in METHOD_MAP:
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                raise ValueError(f"missing operationId for {method.upper()} {path}")
            auth_mode = operation.get("x-sdkwork-auth-mode", "dual-token")
            rate_limit_tier = operation.get("x-sdkwork-rate-limit-tier")
            if rate_limit_tier is not None and rate_limit_tier not in RATE_LIMIT_TIER_MAP:
                raise ValueError(
                    f"unsupported rate limit tier {rate_limit_tier!r} for {operation_id}"
                )
            routes.append((method, path, operation_id, auth_mode, rate_limit_tier))
    routes.sort(key=lambda item: (item[1], item[0]))
    return routes


def render(
    routes: list[tuple[str, str, str, str, str | None]],
    fn_name: str,
    tag: str,
) -> str:
    imports = "HttpMethod, HttpRoute, HttpRouteManifest"
    if any(route[4] is not None for route in routes):
        imports += ", RateLimitTier"
    lines = [
        "// @generated by tools/gen_http_route_manifest_from_openapi.py - do not edit",
        "",
        f"use sdkwork_web_core::{{{imports}}};",
        "",
        "const HTTP_ROUTES: &[HttpRoute] = &[",
    ]
    for method, path, operation_id, auth_mode, rate_limit_tier in routes:
        auth_fn = AUTH_MAP.get(auth_mode)
        if auth_fn is None:
            raise ValueError(f"unsupported auth mode {auth_mode!r} for {operation_id}")
        lines.extend(
            [
                f"    HttpRoute::{auth_fn}(",
                f"        HttpMethod::{METHOD_MAP[method]},",
                f'        "{path}",',
                f'        "{tag}",',
                f'        "{operation_id}",',
            ]
        )
        if rate_limit_tier is None:
            lines.append("    ),")
        else:
            lines.extend(
                [
                    "    )",
                    "    .with_rate_limit_tier(",
                    f"        RateLimitTier::{RATE_LIMIT_TIER_MAP[rate_limit_tier]},",
                    "    ),",
                ]
            )
    lines.extend(
        [
            "];",
            "",
            f"pub fn {fn_name}() -> HttpRouteManifest {{",
            "    HttpRouteManifest::new(HTTP_ROUTES)",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 5:
        print(
            "usage: gen_http_route_manifest_from_openapi.py "
            "<openapi.(json|yaml)> <output.rs> <fn_name> <tag>",
            file=sys.stderr,
        )
        return 1

    openapi_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    fn_name = sys.argv[3]
    tag = sys.argv[4]

    routes = load_routes(openapi_path)
    output_path.write_text(render(routes, fn_name, tag), encoding="utf-8")
    print(f"wrote {len(routes)} routes to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
