// Generated by tools/drive_sdk_generator_runner.mjs from the owner-only Drive OpenAPI input.
// This file is outside generated/server-openapi so SDK ownership metadata does not pollute sdkgen output.

export const sdkMetadata = {
  name: "sdkwork-drive-sdk",
  packageName: "sdkwork-drive-sdk-generated-typescript",
  sdkOwner: "sdkwork-drive",
  apiAuthority: "sdkwork-drive.open",
  language: "typescript",
  standardProfile: "sdkwork-drive-open-v3",
  baseUrl: "http://127.0.0.1:18082",
  apiPrefix: "/open/v3/api",
  sdkDependencies: [],
};

export const operations = {
  "openShareLinks.downloadUrls.create": { method: "POST", path: "/open/v3/api/drive/share_links/{token}/download_url" },
  "openShareLinks.retrieve": { method: "GET", path: "/open/v3/api/drive/share_links/{token}" },
} as const;
